// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC80w5p8s61V96L3i9DFYD-8yvuAubrZY4',
    appId: '1:972190269185:web:5cb117a64765d9ff99a500',
    messagingSenderId: '972190269185',
    projectId: 'nawazsaloon',
    authDomain: 'nawazsaloon.firebaseapp.com',
    storageBucket: 'nawazsaloon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIZOZSgMMraOE9lf0oViF9oBiu03WTh-0',
    appId: '1:972190269185:android:e2ae89777c185d2f99a500',
    messagingSenderId: '972190269185',
    projectId: 'nawazsaloon',
    storageBucket: 'nawazsaloon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9dmKfnAlD32toSdV5J3upTyu-_UyYEUE',
    appId: '1:972190269185:ios:8034f66d7ad50a8e99a500',
    messagingSenderId: '972190269185',
    projectId: 'nawazsaloon',
    storageBucket: 'nawazsaloon.appspot.com',
    iosBundleId: 'com.example.nawazSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9dmKfnAlD32toSdV5J3upTyu-_UyYEUE',
    appId: '1:972190269185:ios:b203ab913486cf7199a500',
    messagingSenderId: '972190269185',
    projectId: 'nawazsaloon',
    storageBucket: 'nawazsaloon.appspot.com',
    iosBundleId: 'com.example.nawazSalon.RunnerTests',
  );
}
