// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgeM_5wcGq7Uj0ZlkoVkOcB6DllrksDA8',
    appId: '1:934758871183:android:fe689a19726ba4422880fa',
    messagingSenderId: '934758871183',
    projectId: 'eventapp-32b57',
    storageBucket: 'eventapp-32b57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84AMPhnCYb4ckaauaUpIuyx4C3a0Uozo',
    appId: '1:934758871183:ios:903efeb0f9c9d4012880fa',
    messagingSenderId: '934758871183',
    projectId: 'eventapp-32b57',
    storageBucket: 'eventapp-32b57.appspot.com',
    androidClientId: '934758871183-3k22jstvlh9r4k0buhmuboml962eph3q.apps.googleusercontent.com',
    iosClientId: '934758871183-0lrpm6j5mm2oserd1l33f35q9kcrsrt8.apps.googleusercontent.com',
    iosBundleId: 'com.elabdtech.eventowner',
  );
}
