// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk91oal4yJ3EKGpNXR3QwtBakGXc9BCDU',
    appId: '1:651973616236:web:5e5cb381fe1ef2155cae49',
    messagingSenderId: '651973616236',
    projectId: 'elabd-tms',
    authDomain: 'elabd-tms.firebaseapp.com',
    storageBucket: 'elabd-tms.appspot.com',
    measurementId: 'G-K1XJD0RH7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG6kImBiGIwXfTr4amUxIQ7ApRoAnhriY',
    appId: '1:651973616236:android:fe866a00f7b1f4ae5cae49',
    messagingSenderId: '651973616236',
    projectId: 'elabd-tms',
    storageBucket: 'elabd-tms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVkDwiQXwoGdyNtfUP2tY-GbjVnzPARA',
    appId: '1:651973616236:ios:960df336977369cd5cae49',
    messagingSenderId: '651973616236',
    projectId: 'elabd-tms',
    storageBucket: 'elabd-tms.appspot.com',
    iosClientId: '651973616236-h83rncdln182hq3ot0q1epk7890qqal3.apps.googleusercontent.com',
    iosBundleId: 'com.elabdtech.elabdtmsapp.elabdTmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVkDwiQXwoGdyNtfUP2tY-GbjVnzPARA',
    appId: '1:651973616236:ios:960df336977369cd5cae49',
    messagingSenderId: '651973616236',
    projectId: 'elabd-tms',
    storageBucket: 'elabd-tms.appspot.com',
    iosClientId: '651973616236-h83rncdln182hq3ot0q1epk7890qqal3.apps.googleusercontent.com',
    iosBundleId: 'com.elabdtech.elabdtmsapp.elabdTmsApp',
  );
}
